# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!


abstract_target 'all' do
    
    pod 'PlayKit', :path => '../../playkit-ios'
    pod 'PlayKit/IMAPlugin', :path => '../../playkit-ios'
    pod 'PlayKit/YouboraPlugin', :path => '../../playkit-ios'

    target 'PlayKitApp' do
    end
    
    target 'IMAPluginSample' do
    end
    
    target 'AnalyticsSample' do
    end

    target 'TracksSample' do
    end 
    
    target 'LocalAssetsSample' do
    end
 end

pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
end


post_install do |installer| 
    installer.pods_project.targets.each do |target| 
        target.build_configurations.each do |config| 
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
            config.build_settings['OTHER_SWIFT_FLAGS'] = '-Xfrontend -warn-long-function-bodies=100'
        end 
    end 
end


target 'ObjCSample' do
    pod 'PlayKit', :path => '../../playkit-ios'
    pod 'PlayKit/IMAPlugin', :path => '../../playkit-ios'
    pod 'PlayKit/YouboraPlugin', :path => '../../playkit-ios'
end

