platform :ios, '8.0'
use_frameworks!

PLAYKIT_GIT='https://github.com/kaltura/playkit-ios.git'
PLAYKIT_TAG='widevine/v0.1.23'

# Uncomment to use a local copy of PlayKit
PLAYKIT_LOCAL='../../playkit-ios'

def definePlayKit(subSpecName)
    if defined? PLAYKIT_LOCAL
        pod "PlayKit/#{subSpecName}" , :path => PLAYKIT_LOCAL
    else
        pod "PlayKit/#{subSpecName}" , :git => PLAYKIT_GIT, :tag => PLAYKIT_TAG
    end
end

source 'https://github.com/kaltura/playkit-ios-widevine.git'
source 'https://github.com/CocoaPods/Specs.git'

abstract_target 'all' do
    
    definePlayKit('Core')

    target 'PlayKitApp' do
    end
    
    target 'IMAPluginSample' do
        definePlayKit('IMAPlugin')
    end
    
    target 'AnalyticsSample' do
        definePlayKit('IMAPlugin')
        definePlayKit('YouboraPlugin')
    end

    target 'TracksSample' do
    end 

    target 'SamplePlugin' do
    end 
    
    target 'LocalAssetsSample' do
        pod 'DownPicker'
        definePlayKit('WidevineClassic')
    end
 end

pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
end


post_install do |installer| 
    installer.pods_project.targets.each do |target| 
        target.build_configurations.each do |config| 
            config.build_settings['SWIFT_VERSION'] = '3.0'
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
        end 
    end 
end


target 'ObjCSample' do
    definePlayKit('Core')
    definePlayKit('IMAPlugin')
    #definePlayKit('WidevineClassic')
definePlayKit('YouboraPlugin')
end

