source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0' # (define required version)

# Uncomment to use a local copy of PlayKit
#PLAYKIT_LOCAL='../../playkit-ios'

target 'KalturaStatsSample' do
    if defined? PLAYKIT_LOCAL
        pod "PlayKit" , :path => PLAYKIT_LOCAL
    	pod 'PlayKit/KalturaStatsPlugin', :path => PLAYKIT_LOCAL
    else
	pod 'PlayKit'
    	pod 'PlayKit/KalturaStatsPlugin'
    end
end

target 'KalturaStatsSample-Swift' do
    if defined? PLAYKIT_LOCAL
        pod "PlayKit" , :path => PLAYKIT_LOCAL
    	pod 'PlayKit/KalturaStatsPlugin', :path => PLAYKIT_LOCAL
    else
	pod 'PlayKit'
    	pod 'PlayKit/KalturaStatsPlugin'
    end
end

pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
end

post_install do |installer| 
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config| 
            config.build_settings['SWIFT_VERSION'] = '3.0'
      	    config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
        end 
  	end 
end
