source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

# Uncomment to use a local copy of PlayKit
#PLAYKIT_LOCAL='../../playkit-ios'
#PLAYKIT_IMA_LOCAL='../../playkit-ios-ima'

platform :ios, '9.0' # (define required version)

PLAYKIT_GIT='https://github.com/kaltura/playkit-ios.git'
PLAYKIT_IMA_GIT='https://github.com/kaltura/playkit-ios-ima.git'

PLAYKIT_BRANCH=ENV['PK_BRANCH'] || 'develop'
PLAYKIT_IMA_BRANCH=ENV['PK_IMA_BRANCH'] || 'develop'

abstract_target 'SharedPods' do
    if defined? PLAYKIT_LOCAL
        pod 'PlayKit', :path => PLAYKIT_LOCAL
        pod 'PlayKit/YouboraPlugin', :path => PLAYKIT_LOCAL
        else
        pod 'PlayKit', :git => PLAYKIT_GIT, :branch => PLAYKIT_BRANCH
        pod 'PlayKit/YouboraPlugin', :git => PLAYKIT_GIT, :branch => PLAYKIT_BRANCH
    end
    
    if defined? PLAYKIT_IMA_LOCAL
        pod 'PlayKit_IMA', :path => PLAYKIT_IMA_LOCAL
        else
        pod 'PlayKit_IMA', :git => PLAYKIT_IMA_GIT, :branch => PLAYKIT_IMA_BRANCH
    end
    
    target 'IMASample'
    target 'IMASample-swift'
end


pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
            if target.name == 'PlayKit'
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end

