source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0' # (define required version)

# Uncomment to use a local copy of PlayKit
#PLAYKIT_LOCAL='../../playkit-ios'
#PLAYKIT_GOOGLECAST_LOCAL='../../playkit-ios-googlecast'

# Uncomment to use a git copy
#PLAYKIT_GIT='https://github.com/kaltura/playkit-ios.git'
#PLAYKIT_GOOGLECAST_GIT='https://github.com/kaltura/playkit-ios-googlecast.git'

PLAYKIT_BRANCH=ENV['PK_BRANCH'] || 'develop'
PLAYKIT_GOOGLECAST_BRANCH=ENV['PKGC_BRANCH'] || 'develop'

abstract_target 'SharedPods' do
  if defined? PLAYKIT_LOCAL
    pod 'PlayKit', :path => PLAYKIT_LOCAL
    else
    if defined? PLAYKIT_GIT
      pod 'PlayKit', :git => PLAYKIT_GIT, :branch => PLAYKIT_BRANCH
      else
      pod 'PlayKit', '~> 3.12'
    end
  end
  
  if defined? PLAYKIT_GOOGLECAST_LOCAL
    pod 'PlayKitGoogleCast', :path => PLAYKIT_GOOGLECAST_LOCAL
    else
    if defined? PLAYKIT_GOOGLECAST_GIT
      pod 'PlayKitGoogleCast', :git => PLAYKIT_GOOGLECAST_GIT, :branch => PLAYKIT_GOOGLECAST_BRANCH
      else
      pod 'PlayKitGoogleCast', '~> 1.3'
    end
  end

  target 'ChromecastSample'
end
