source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0' # (define required version)

PLAYKIT_GIT='https://github.com/kaltura/playkit-ios.git'
PLAYKIT_BRANCH=ENV['PK_BRANCH'] || 'master'

target 'ChangeMediaSample' do
    pod 'PlayKit', :git => PLAYKIT_GIT, :branch => PLAYKIT_BRANCH
end

target 'ChangeMediaSample-Swift' do
    pod 'PlayKit', :git => PLAYKIT_GIT, :branch => PLAYKIT_BRANCH
end

pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
end

post_install do |installer| 
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config| 
            config.build_settings['SWIFT_VERSION'] = '3.0'
      	    config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
        end 
  	end 
end
