source 'https://github.com/CocoaPods/Specs.git'

#inhibit_all_warnings!
use_frameworks!

platform :ios, '9.0' # (define required version)

# Uncomment to use a local copy of PlayKit
#PLAYKIT_LOCAL='../../playkit-ios'
#PLAYKIT_PROVIDERS_LOCAL='../../playkit-ios-providers'
#PLAYKIT_YOUBORA_LOCAL='../../playkit-ios-youbora'
#PLAYKIT_VR_LOCAL='../../playkit-ios-vr'
METALSCOPE_LOCAL='../../MetalScope'

# Uncomment to use a git copy
#PLAYKIT_GIT='https://github.com/kaltura/playkit-ios.git'
#PLAYKIT_PROVIDERS_GIT='https://github.com/kaltura/playkit-ios-providers.git'
#PLAYKIT_YOUBORA_GIT='https://github.com/kaltura/playkit-ios-youbora.git'
#PLAYKIT_VR_GIT='https://github.com/kaltura/playkit-ios-vr.git'

PLAYKIT_BRANCH=ENV['PK_BRANCH'] || 'develop'
PLAYKIT_PROVIDERS_BRANCH=ENV['PKP_BRANCH'] || 'develop'
PLAYKIT_YOUBORA_BRANCH=ENV['PKY_BRANCH'] || 'develop'
PLAYKIT_VR_BRANCH=ENV['PK_VR_BRANCH'] || 'develop'

abstract_target 'SharedPods' do
  if defined? PLAYKIT_LOCAL
    pod 'PlayKit', :path => PLAYKIT_LOCAL
    else
    if defined? PLAYKIT_GIT
      pod 'PlayKit', :git => PLAYKIT_GIT, :branch => PLAYKIT_BRANCH
      else
      pod 'PlayKit'
    end
  end
  
  if defined? PLAYKIT_PROVIDERS_LOCAL
    pod 'PlayKitProviders', :path => PLAYKIT_PROVIDERS_LOCAL
    else
    if defined? PLAYKIT_PROVIDERS_GIT
      pod 'PlayKitProviders', :git => PLAYKIT_PROVIDERS_GIT, :branch => PLAYKIT_PROVIDERS_BRANCH
      else
      pod 'PlayKitProviders'
    end
  end
  
  if defined? PLAYKIT_YOUBORA_LOCAL
    pod 'PlayKitYoubora', :path => PLAYKIT_YOUBORA_LOCAL
    else
    if defined? PLAYKIT_YOUBORA_GIT
      pod 'PlayKitYoubora', :git => PLAYKIT_YOUBORA_GIT, :branch => PLAYKIT_YOUBORA_BRANCH
      else
      pod 'PlayKitYoubora'
    end
  end
  
  if defined? PLAYKIT_VR_LOCAL
    pod 'PlayKitVR', :path => PLAYKIT_VR_LOCAL
    else
    if defined? PLAYKIT_VR_GIT
      pod 'PlayKitVR', :git => PLAYKIT_VR_GIT, :branch => PLAYKIT_VR_BRANCH
      else
      pod 'PlayKitVR'
    end
  end
  
  #   Forked temporary until MetalScope updates to Swift 4
  if defined? METALSCOPE_LOCAL
    pod 'MetalScope', :path => METALSCOPE_LOCAL
    else
    pod 'MetalScope', :git => 'https://github.com/kaltura/MetalScope.git', :branch => 'swift-4.2'
  end
  
  target 'VRSample'
end
