source 'https://github.com/CocoaPods/Specs.git'

#inhibit_all_warnings!
use_frameworks!

platform :ios, '9.0' # (define required version)

# Uncomment to use a local copy of PlayKit
PLAYKIT_LOCAL='../../playkit-ios'
#PLAYKIT_VR_LOCAL='../../playkit-ios-vr'
#METALSCOPE_LOCAL='../../MetalScope'

PLAYKIT_GIT='https://github.com/kaltura/playkit-ios.git'
PLAYKIT_BRANCH=ENV['PK_BRANCH'] || 'develop'

PLAYKIT_VR_GIT='https://github.com/kaltura/playkit-ios-vr.git'
PLAYKIT_VR_BRANCH=ENV['PK_VR_BRANCH'] || 'develop'

abstract_target 'SharedPods' do
    if defined? PLAYKIT_LOCAL
        pod 'PlayKit', :path => PLAYKIT_LOCAL
        pod 'PlayKit/YouboraPlugin', :path => PLAYKIT_LOCAL
        else
        pod 'PlayKit', :git => PLAYKIT_GIT, :branch => PLAYKIT_BRANCH
        pod 'PlayKit/YouboraPlugin', :git => PLAYKIT_GIT, :branch => PLAYKIT_BRANCH
    end
    
    if defined? PLAYKIT_VR_LOCAL
        pod 'PlayKitVR', :path => PLAYKIT_VR_LOCAL
        else
        pod 'PlayKitVR', :git => PLAYKIT_VR_GIT, :branch => PLAYKIT_VR_BRANCH
    end
    
#   Forked temporary until MetalScope updates to Swift 4
    if defined? METALSCOPE_LOCAL
        pod 'MetalScope', :path => METALSCOPE_LOCAL
        else
        pod 'MetalScope', :git => 'https://github.com/kaltura/MetalScope.git', :branch => 'swift-4.2'
    end
    
    target 'VRSample'
    
end
