project 'PlayKitAppleTVSample.xcodeproj'

platform :tvos, '9.0' # (define required version)

use_frameworks!

# Uncomment to use a local copy of PlayKit
PLAYKIT_LOCAL='../../playkit-ios'
PLAYKIT_ADMANAGER_LOCAL='../../playkit-ios-admanager-plugin'

PLAYKIT_GIT='https://github.com/kaltura/playkit-ios.git'
PLAYKIT_BRANCH=ENV['PK_BRANCH'] || 'develop'

PLAYKIT_ADMANAGER_GIT='https://github.com/kaltura/playkit-ios-admanager-plugin.git'
PLAYKIT_ADMANAGER_BRANCH=ENV['PK_AD_BRANCH'] || 'develop'

abstract_target 'SharedPods' do
    if defined? PLAYKIT_LOCAL
        pod 'PlayKit', :path => PLAYKIT_LOCAL
        pod 'PlayKit/YouboraPlugin' , :path => PLAYKIT_LOCAL
        else
        pod 'PlayKit', :git => PLAYKIT_GIT, :branch => PLAYKIT_BRANCH
        pod 'PlayKit/YouboraPlugin' , :git => PLAYKIT_GIT, :branch => PLAYKIT_BRANCH
    end
    
    if defined? PLAYKIT_ADMANAGER_LOCAL
        pod 'PlayKitAdManagerPlugin', :path => PLAYKIT_ADMANAGER_LOCAL
        else
        pod 'PlayKitAdManagerPlugin', :git => PLAYKIT_ADMANAGER_GIT, :branch => PLAYKIT_ADMANAGER_BRANCH
    end
    
    target 'PlayKitAppleTVSample'
    
end
