project 'PlayKitAppleTVSample.xcodeproj'

platform :tvos, '9.0' # (define required version) 

use_frameworks!

PLAYKIT_GIT='https://github.com/kaltura/playkit-ios.git'
PLAYKIT_BRANCH=ENV['PK_BRANCH'] || 'master'

target 'PlayKitAppleTVSample' do
  pod 'PlayKit', :git => PLAYKIT_GIT, :branch => PLAYKIT_BRANCH
  pod 'PlayKit/YouboraPlugin' , :git => PLAYKIT_GIT, :branch => PLAYKIT_BRANCH
  pod 'PlayKitAdManagerPlugin', :path => '../../playkit-ios-ads'
end

pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
end

post_install do |installer| 
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config| 
            config.build_settings['SWIFT_VERSION'] = '4.0'
      	    config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
        end 
    end 
end
