source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0' # (define required version)

# Uncomment to use a local copy of PlayKit
PLAYKIT_LOCAL='../../playkit-ios'
PLAYKIT_YOUBORA_LOCAL='../../playkit-ios-youbora'

# Uncomment to use a git copy
#PLAYKIT_GIT='https://github.com/kaltura/playkit-ios.git'
PLAYKIT_YOUBORA_GIT='https://github.com/kaltura/playkit-ios-youbora.git'

PLAYKIT_BRANCH=ENV['PK_BRANCH'] || 'develop'
PLAYKIT_YOUBORA_BRANCH=ENV['PKY_BRANCH'] || 'develop'

abstract_target 'SharedPods' do
  if defined? PLAYKIT_LOCAL
    pod 'PlayKit', :path => PLAYKIT_LOCAL
    else
    if defined? PLAYKIT_GIT
      pod 'PlayKit', :git => PLAYKIT_GIT, :branch => PLAYKIT_BRANCH
      else
      pod 'PlayKit'
    end
  end
  
  if defined? PLAYKIT_YOUBORA_LOCAL
    pod 'PlayKitYoubora', :path => PLAYKIT_YOUBORA_LOCAL
    else
    if defined? PLAYKIT_YOUBORA_GIT
      pod 'PlayKitYoubora', :git => PLAYKIT_YOUBORA_GIT, :branch => PLAYKIT_YOUBORA_BRANCH
      else
      pod 'PlayKitYoubora'
    end
  end

pod 'KalturaNetKit', :path => '../../netkit-ios'
pod 'PlayKitUtils', :path => '../../playkit-ios-utils'
  
  target 'YouboraSample'
  target 'YouboraSample-Swift'
end
