
platform :ios, '9.0'

target 'OVPStarter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OVPStarter
  pod 'PlayKit', :path => '../../playkit-ios'
	pod 'PlayKitKava', :path => '../../playkit-ios-kava'

end
